from trainops_prompts.templates import (
    CLARIFICATION_PROMPT,
    DATASET_REVIEW_PROMPT,
    EVALUATION_ANALYSIS_PROMPT,
    PLAN_PROMPT,
    PUBLICATION_PROMPT,
    RESEARCH_PROMPT,
)

__all__ = [
    "CLARIFICATION_PROMPT",
    "DATASET_REVIEW_PROMPT",
    "EVALUATION_ANALYSIS_PROMPT",
    "PLAN_PROMPT",
    "PUBLICATION_PROMPT",
    "RESEARCH_PROMPT",
]

